github:
  features:
    # Enable issue management
    issues: true
    # Enable wiki
    wiki: true

    
  protected_branches:
    master:
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 2
