github:
  features:
    # Enable issue management
    issues: true
    # Enable wiki
    wiki: true

enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  false
    
  protected_branches:
    master:
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 2
