dist: trusty
 
language: java

jdk:
    - oraclejdk8
    - oraclejdk9
    - oraclejdk11
    - openjdk8

before_install:
  - echo 'MAVEN_OPTS="$MAVEN_OPTS -Xmx1024m -XX:MaxPermSize=512m -XX:+BytecodeVerificationLocal"' >> ~/.mavenrc
  - cat ~/.mavenrc
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use "$CUSTOM_JDK"; fi

script:
  - travis_retry mvn -B clean apache-rat:check
  - travis_retry mvn -B clean install cobertura:cobertura

after_success:
  - bash < (curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
